### ISSUE TITLE
Error JwtPayload

### ISSUE THREAD

**Issue by MyFuneral** [Linus2punkt0/bluesky-crossposter#41]
Hello I have this error since yesterday morning :
TypeError: JwtPayload.__init__() got an unexpected keyword argument 'aud'

**Comment by Linus2punkt0** [comment]
Bluesky updated something on their end which made atproto not work. There has since been a new version of atproto released that fixes this, so try updating and it should be all good!

**Comment by MyFuneral** [comment]
Sorry but I'm a noob, so how do you update these files?  I'm on Windows

**Comment by Linus2punkt0** [comment]
Not fully sure how you did the install, but "pip install -U atproto" is generally how you would do it.

**Comment by MyFuneral** [comment]
I did it with the file : requirements.txt
sorry for this message and thank you in any case for this function

**Comment by Linus2punkt0** [comment]
The requirements.txt was updated when then new version of atproto was released, so you can download a new version using git (if you cloned the repo) or just downloading the specific file. Since it's just the one dependency that has been updated you don't have to though, you can just upgrade it on its own.
