### ISSUE TITLE
[FEATURE] Telegram support

### ISSUE THREAD

**Issue by hynet-mel** [Linus2punkt0/bluesky-crossposter#65]
Hello! Just thought I'd drop this wish around here, since I'm looking for a solution to crosspost my art from a Telegram channel out to other channels like Bluesky, Mastodon and/or twitter.

Are there any plans to support Telegram bots added to channels to crosspost?
I might be willing to implement that in a PR but thought I'd make a issue about it first

**Comment by Linus2punkt0** [comment]
There have been no plans for telegram, though some loose plans exists for making mastodon available as input instead of bluesky, and by extension add the possibility for other input sources. This will however require a rewrite of the way posts are stored in the "database", as well as Bluesky needing to be added as an output, so it would have to come as a part of a larger rewrite.

I'm not entirely sure how well telegram maps onto the framework of posts with specific IDs, my feeling is that it might work better as a fork that can be more specifically geared towards Telegram, but I might be wrong.

**Comment by hynet-mel** [comment]
> There have been no plans for telegram, though some loose plans exists for making mastodon available as input instead of bluesky, and by extension add the possibility for other input sources. This will however require a rewrite of the way posts are stored in the "database", as well as Bluesky needing to be added as an output, so it would have to come as a part of a larger rewrite.

Fair! I just noticed that the BSKY output wasn't present either. 

> I'm not entirely sure how well telegram maps onto the framework of posts with specific IDs, my feeling is that it might work better as a fork that can be more specifically geared towards Telegram, but I might be wrong.

Alright, I mean, I'll have to fork and try it out there first, so I'll see from there if I can cook something up that is able to do that :)
You'll see a PR incase I think it's still a good fit for this repository, otherwise it'll just live on as a fork!
